### ISSUE TITLE
 Download database for Human stops

### ISSUE THREAD

**Issue by ysuzuki1978** [gexijin/idepGolem#485]
I installed it on an intel mac using a docker container as instructed.
When I access locahost:3838, a screen appears, but the Download database for Human stops in the middle of the process and does not proceed.
I have tried on other macs and the same situation.
Please let me know how to improve this situation.
![スクリーンショット 2023-06-13 13 22 45](https://github.com/gexijin/idepGolem/assets/42367694/54a71f14-c258-4cd9-ae8b-36089cbddb16)

**Comment by gexijin** [comment]
Hi Dr. Suzuki, Thanks for the feedback. I think this is fixed in the most recent update. There is a setting that if download lasts more than 5 minutes, it will stop.  See this issue: https://github.com/gexijin/idepGolem/issues/490

Also, even if the progress bar stuck, it might already downloaded the database. So try reload the app by visiting: localhost:3838. 

I am closing this for now. Please let me know problem persists by commenting on the other issue.
